language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="mrmime"
   - DISTRO="alpine"
 matrix:
   - OCAML_VERSION=4.08 TESTS=true
   - OCAML_VERSION=4.09 TESTS=true
   - OCAML_VERSION=4.10 TESTS=true
   - OCAML_VERSION=4.11 TESTS=true
   - OCAML_VERSION=4.12 TESTS=true
