language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="mrmime"
   - DISTRO="alpine"
   - PINS="crowbar:https://github.com/stedolan/crowbar.git bigarray-overlap:https://github.com/dinosaure/overlap.git emile:https://github.com/dinosaure/emile.git"
 matrix:
   - OCAML_VERSION=4.07 TESTS=true
   - OCAML_VERSION=4.08 TESTS=true
   - OCAML_VERSION=4.09 TESTS=true
